spring:
  application:
    name: editor-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:/db/migration/{vendor}
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:15432/appdb
#    username: postgres
#    password: root